name: Advocate2018
channels:
  - pjamesjoyce
  - defaults
dependencies:
  - ipykernel
  - numpy
  - opencv=3.4.2
  - pandas
  - pillow
  - scipy
  - matplotlib
  - imageio
  - pip:
    - opencv-python==4.0.1
    -imutils
